### PR TITLE
Disable CORBA LongDouble by default

### PR DESCRIPTION
**Pull request by abogani**
Signed-off-by: Alessio Igor Bogani <alessio.bogani@elettra.eu>

### CODE REVIEW

**Comment by btgoodwin** [comment]
@abogani,

Thank you for the contribution.  We've started following the yocto release branch setup, so `master` is actually pretty far behind now (we're keeping it for some historical projects, but that's it).  This patch has been pulled into the `thud` and `rocko` branches already with a tweak to be for all 32-bit ARM only vs. specifically `zynq` (Xilinx) parts as before:

https://github.com/Geontech/meta-redhawk-sdr/blob/rocko/recipes-deps/omniorb/omniorb_4.2.3.bb#L47

Does that fully fix it for you?

**Comment by abogani** [comment]
@btgoodwin, 

[...]
> Thank you for the contribution. We've started following the yocto release branch setup, so `master` is actually pretty far behind now (we're keeping it for some historical projects, but that's it).

It isn't completely true: in the Yocto project the master branch is the most updated version of the code (actually it contains what become zeus release soon).  There is also master-next but it is more a branch for Yocto developer than for everyone else (and for this reason it is rebased very often).

> This patch has been pulled into the `thud` and `rocko` branches already with a tweak to be for all 32-bit ARM only vs. specifically `zynq` (Xilinx) parts as before:
> 
> https://github.com/Geontech/meta-redhawk-sdr/blob/rocko/recipes-deps/omniorb/omniorb_4.2.3.bb#L47
> 
> Does that fully fix it for you?

Yes it does but I don't like it actually: I have other architectures in the field so I would like to avoid incompatibility because some naive programmer choose to use it. Moreover we are using warrior and we have already planned to switch to zeus when it'll became officially available.

Thanks for all!

**Comment by btgoodwin** [comment]
Nice to hear REDHAWK builds on warrior!  Were there any major changes or
challenges?

I would be happy to accept EXTRA_OECONF appends for those other
architectures if you can share them.

**Comment by abogani** [comment]
@btgoodwin,

Actually it also works on current master branch of Yocto (that will become Zeus soon). I think that has proven your good work on OmniORB recipe!

**Comment by btgoodwin** [comment]
Nice! Thanks!

**Pull request closed without merging**
