### PR TITLE
patch changes

### PR DESCRIPTION
**Pull request by KAUSHAL1986**

### CODE REVIEW

**Comment by KAUSHAL1986** [comment]
In that file also we have to replace it with config.mk.in.patch and then it will work

**Comment by rodrigo455** [comment]
renaming the patch was just to better refer the file to be patched? otherwise it is not of much use. I agree with the "Update fftw3_removal.patch" commit though.

**Comment by btgoodwin** [comment]
I apologize for the delay on this; the fftw3 removal patch came up in a recent project for us as well and will be included in the next push which will be RH 2.2.1 with a slew of other fixes including ComponentHost.spd.xml being patched for the embedded architecture.  That latter patch however will be causing trouble when running a domain that is a different architecture than the GPPs in the system since the domain's version needs to have all possible implementations in the SPD as well as the executable to distribute (part of the shared address space upgrades that came in the 2.1.x series of patches).

**Comment by btgoodwin** [comment]
Closing now that 2.2.1 and 2.2.2 support have been pulled forward that include that patch and other fixes.  Thank you again for bringing this to our attention!

**Pull request closed without merging**
